name: phoenix_socket
description: >-
  PhoenixSocket provides a feature-complete implementation
  of Phoenix Sockets, using a single API based on StreamChannels
  compatible with any deployment of Flutter.
version: 0.6.4
repository: https://www.github.com/matehat/phoenix-socket-dart
homepage: https://www.github.com/matehat/phoenix-socket-dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  equatable: ^2.0.3
  logging: ^1.0.0
  meta: ^1.2.4
  pedantic: ^1.9.2
  quiver: ^3.0.0
  rxdart: '>=0.26.0 <0.28.0'
  web_socket_channel: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.11.1
